### ISSUE TITLE
Add Internal Sort

### ISSUE THREAD

**Issue by nas5w** [nas5w/javascript-patterns#15]
Add Internal Sort and associated tests

**Comment by arabyalhomsi** [comment]
Internal Sort does not seem to be a sorting algorithm but rather a collection of sorting algorithms, as this webpage shows:
https://www.cs.cmu.edu/~adamchik/15-121/lectures/Sorting%20Algorithms/sorting.html

**Comment by nas5w** [comment]
Correct, I'll close this and remove from readme. External sort too
