### ISSUE TITLE
Add Jump Search and associated tests

### ISSUE THREAD

**Issue by nas5w** [nas5w/javascript-patterns#30]
Add Jump Search and associated tests

**Comment by gautam678** [comment]
I'll take this too

**Comment by nas5w** [comment]
You’re a machine!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gautam678** [comment]
Getting Hactoberfest PRs in :-P

**Comment by gautam678** [comment]
https://github.com/nas5w/javascript-patterns/pull/57
