### ISSUE TITLE
Add Fibonacci Search and associated tests

### ISSUE THREAD

**Issue by nas5w** [nas5w/javascript-patterns#35]
Add Fibonacci Search and associated tests

**Comment by natehole** [comment]
Please assign to me
I would like to work on this in my free time in the next couple of days.

**Comment by nas5w** [comment]
All yours!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ShantanuShinde** [comment]
I will like to work on this

**Comment by ShantanuShinde** [comment]
https://github.com/nas5w/javascript-patterns/pull/55
here is my pull request. Fixed the issue

**Comment by ShantanuShinde** [comment]
Is my Fibonacci search code ok?
