### ISSUE TITLE
Add Builder Pattern and associated tests

### ISSUE THREAD

**Issue by nas5w** [nas5w/javascript-patterns#43]
Add Builder Pattern and associated tests

**Comment by fluffynuts** [comment]
I'd like to take this one (:

**Comment by fluffynuts** [comment]
Hm, it looks like there is an example of the builder pattern in this repo already; however, having used builder _a lot_, I feel that I could bring a new perspective. I'll only open a PR if you think that might be useful (:

In particular: I've found that builders which store object state can be prone to subtle misunderstandings later down the line. Builders which I create rather store transforms to be applied to to an initial state to arrive at a final result.
