### ISSUE TITLE
Add links to code in README

### ISSUE THREAD

**Issue by nas5w** [nas5w/javascript-patterns#54]
There should be links in the main README for each algorithm, design pattern, and technique that take you to the code. This would be much better than the users having to find the code themselves.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by klauskpm** [comment]
I would like to work on this!

**Comment by ShantanuShinde** [comment]
I completed this. Here is the pull request:https://github.com/nas5w/javascript-patterns/pull/55
Please review.

**Comment by dishijn2** [comment]
i want to work on this

**Comment by ShantanuShinde** [comment]
I updated the links to proper codes. The earlier was incorrect
https://github.com/nas5w/javascript-patterns/pull/55

**Comment by ShantanuShinde** [comment]
I will PR a proper repo branch for each issue
